version: "3.3"
services:
  learnet_ui:
    build: .
    container_name: learnet_ui
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:learnet.io"
      - "traefik.port=80"
      - "traefik.backend=learnet_ui"
      - "traefik.docker.network=traefik_network"
      - "traefik.frontend.entryPoints=http,https"
      networks:
        - traefik_network

networks:
  traefik_network:
    external: true