version: "3.3"
services:
  codeseer_ui:
    build: .
    container_name: codeseer_ui
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:codeseer.net"
      - "traefik.port=80"
      - "traefik.backend=codeseer_ui"
      - "traefik.docker.network=traefik_network"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true